### ISSUE TITLE
Question,

### ISSUE THREAD

**Issue by wioxjk** [ShepherdJerred/Portal#2]
Hi,

First of all, this template is fantastic! I really love it and it is simple to modify (even for a non webbdev like me :) )
I was wondering if it possible to add a animation that occur when I click it? But all the current animations should still be there.
The idea is to make some cool effect, for example:
You click the "button", a animation (pulse) occur and a iframe with dynmap slides in.

the site is currently on https://portal.selea.se 

And btw, the "live preview" is not live anymore :)

**Comment by ShepherdJerred** [comment]
Sure it's possible, but you'd have to modify the template. Yeah, the live preview gets thrown around, I'll try to fix it when I get the chance.
